name: ${{ parameters.VersionNumberMajor }}.${{ parameters.VersionNumberMinor }}$(Rev:.rrrr)


parameters:
- name: VersionNumberMajor
  displayName: 'Version Number : Major'
  type: string
  default: '0'  
  
- name: VersionNumberMinor
  displayName: 'Version Number : Minor'
  type: string
  default: '0'  
  
- name: BuildConfiguration
  displayName: Release or Debug
  type: string
  default: Release
  values:
  - Release
  - Debug

- name: BuildPool
  displayName: 'Build Pool'
  type: string
  default: 'DCT Build Pool'
  values:
  - 'DCT Build Pool'
  - 'DCT'
  
- name: BuildPoolDemand
  displayName: 'Build Pool Demand'
  type: string
  default: 'IsBuildServer'
  values:
  - 'IsBuildServer'
  - 'IsBuildServerDAS'
  - 'IsBuildServer_Old'
  - 'IsBuildServer_TEST'


stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: BuildWinodows
    displayName: Build Artifacts
    
    pool:
      name: ${{ parameters.BuildPool }} 
      demands:
      - ${{ parameters.BuildPoolDemand }} 
          
    variables:  
      "Nuget.Feed": 'dct-pkg'  
      BuildPlatform: 'Any CPU'
      BuildPlatformX64: 'x64'  

    steps:
    # - task: DotNetCoreInstaller@0
    #   displayName: 'Use .NET Core sdk 2.2.106'
    #   inputs:
    #     version: 2.2.106

    - task: DotNetCoreCLI@2
      displayName: 'Restore Provider Payments Messages'
      inputs:
        command: restore
        projects: src/SFA.DAS.Payments.ProviderPayments.Messages/SFA.DAS.Payments.ProviderPayments.Messages.csproj
        vstsFeed: '${{ parameters.NugetFeed }}'

    - task: DotNetCoreCLI@2
      displayName: 'Build Provider Payments Messages'
      inputs:
        projects: src/SFA.DAS.Payments.ProviderPayments.Messages/SFA.DAS.Payments.ProviderPayments.Messages.csproj
        arguments: '--configuration ${{ parameters.BuildConfiguration }} --no-restore -p:version="${{ parameters.BuildNumber}}" -p:FileVersion="${{ parameters.BuildFileVersion}}"'      
      enabled: false

    - task: DotNetCoreCLI@2
      displayName: 'Pack Provider Payments Messages'
      inputs:
        command: pack
        packagesToPack: src/SFA.DAS.Payments.ProviderPayments.Messages/SFA.DAS.Payments.ProviderPayments.Messages.csproj
        arguments: '--configuration ${{ parameters.BuildConfiguration }} --no-restore -p:version="${{ parameters.BuildNumber}}" -p:FileVersion="${{ parameters.BuildFileVersion}}"'
        versioningScheme: byBuildNumber

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: '**/*.nupkg'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/ProviderPayments'    

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Packages'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
